id: I486BD994
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T22:24:28+00:00'
last_modified: '2022-06-08T13:15:13.771967+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W9683
  title: གསུང་འབུམ། སྐལ་ལྡན་རྒྱ་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    84AD:
      image_group_id: I5167
      title: ''
      total_pages: 470
      order: 1
      base_file: 84AD.txt
    9E62:
      image_group_id: I5168
      title: ''
      total_pages: 474
      order: 2
      base_file: 9E62.txt
    8C80:
      image_group_id: I5169
      title: ''
      total_pages: 408
      order: 3
      base_file: 8C80.txt
    20F7:
      image_group_id: I5170
      title: ''
      total_pages: 438
      order: 4
      base_file: 20F7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
