id: I486BD994
legacy_id: P010391
ocr_import_info:
  bdrc_scan_id: W9683
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T22:21:38'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T05:10:42.795873+00:00'
last_modified: 2022-09-04 13:11:27.055391
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W9683
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW9683
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། སྐལ་ལྡན་རྒྱ་མཚོ།
  author: ཤར་སྐལ་ལྡན་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.6075545242265528
  ocr_word_median_confidence_index: 0.6600000262260437
quality: null
bases:
  I5170:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5170
      total_pages: 438
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I5170.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6112237490433566
    legacy_id: v004
  I5168:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5168
      total_pages: 474
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I5168.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.6173740075457503
    legacy_id: v002
  I5167:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5167
      total_pages: 470
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5167.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6042105139404726
    legacy_id: v001
  I5169:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5169
      total_pages: 408
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I5169.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.5962009942967422
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
